data:extend({
	{
		type = "item",
		name = "airchest_1",
		icon = "__DogsMultiLib__/prototypes/airchest/g/wooden-chest.png",
		subgroup = "storage",
		place_result = "airchest_1",
		stack_size = 210,
		icon_size = 32,
	},
	{
		type = "item",
		name = "airchest_2",
		icon = "__DogsMultiLib__/prototypes/airchest/g/iron-chest.png",
		subgroup = "storage",
		place_result = "airchest_2",
		stack_size = 210,
		icon_size = 32,
	},
	{
		type = "item",
		name = "airchest_3",
		icon = "__DogsMultiLib__/prototypes/airchest/g/steel-chest.png",
		subgroup = "storage",
		place_result = "airchest_3",
		stack_size = 210,
		icon_size = 32,
	},
	{
		type = "item",
		name = "coal-filter",
		icon = "__DogsMultiLib__/prototypes/airchest/g/coal-filter.png",
		subgroup = "storage",
		place_result = "coal-filter",
		stack_size = 20,
		icon_size = 32,
	},
	{
		type = "item",
		name = "idiamond",
		icon = "__DogsMultiLib__/prototypes/airchest/g/idiamond.png",
		subgroup = "storage",
		place_result = "idiamond",
		stack_size = 20,
		icon_size = 32,
	},
	{
		type = "item",
		name = "airchest_4",
		icon = "__DogsMultiLib__/prototypes/airchest/g/diamond-chest.png",
		subgroup = "storage",
		place_result = "airchest_4",
		stack_size = 20,
		icon_size = 32,
	},
})
